// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 8.7
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_fade(c,a,b){var e=jQuery,g=e(this),d=e(".ws_list",b),h={position:"absolute",left:0,top:0,width:"100%",height:"100%",maxHeight:"none",maxWidth:"none",transform:"translate3d(0,0,0)"},f=e("<div>").addClass("ws_effect ws_fade").css(h).css("overflow","hidden").appendTo(b);this.go=function(i,j){var k=e(a.get(i)),m={width:k.width(),height:k.height()};k=k.clone().css(h).css(m).appendTo(f);if(!c.noCross){var l=e(a.get(j)).clone().css(h).css(m).appendTo(f);wowAnimate(l,{opacity:1},{opacity:0},c.duration,function(){l.remove()})}wowAnimate(k,{opacity:0},{opacity:1},c.duration,function(){g.trigger("effectEnd");k.remove()})}};// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 8.7
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container1").wowSlider({effect:"fade",prev:"",next:"",duration:20*100,delay:90*100,width:1024,height:768,autoPlay:true,autoPlayVideo:true,playPause:true,stopOnHover:true,loop:false,bullets:0,caption:false,captionEffect:"none",controls:true,controlsThumb:false,responsive:2,fullScreen:true,gestures:2,onBeforeStep:0,images:[{src:"./pic_1.jpg",title:"pic 1"},{src:"./pic_2.jpg",title:"pic 2"},{src:"./pic_3.jpg",title:"pic 3"},{src:"./pic_4.jpg",title:"pic 4"},{src:"./pic_5.jpg",title:"pic 5"},{src:"./pic_6.jpg",title:"pic 6"},{src:"./pic_7.jpg",title:"pic 7"},{src:"./pic_8.jpg",title:"pic 8"},{src:"./pic_9.jpg",title:"pic 9",href:"http://wowslider.com"},{src:"./pic_10.jpg",title:"pic 10"}]});